apiVersion: v2
appVersion: "1.0"
description: Divorce - Petitioner frontend
name: div-pfe
version: 2.0.28
dependencies:
  - name: nodejs
    version: 3.0.2
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: redis
    version: 17.7.2
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - pr
  - name: idam-pr
    version: 2.2.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - idam-pr
