nodejs:
    applicationPort: 3000
    aadIdentityName: divorce
    image: "hmctspublic.azurecr.io/div/pfe:latest"
    ingressHost: "div-pfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal" # override in public facing environments
    environment:
        MICROSERVICE_NAME: "divorce_frontend"
        # Info provider config
        REFORM_SERVICE_NAME: "pfe"
        REFORM_TEAM: "div"
        # Analytics
        GOOGLE_ANALYTICS_TRACKING_URL: "http://www.google-analytics.com/collect"
        # Security config
        HPKP_MAX_AGE: "86400"
        HPKP_SHAS: "Naw+prhcXSIkbtYJ0t7vAD+Fc92DWL9UZevVfWBvids=,klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=,grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="

        # Why is there 2 values for the same thing?
        DEPLOYMENT_ENV: "{{ .Values.global.environment }}"
        REFORM_ENVIRONMENT: "{{ .Values.global.environment }}"

        GOOGLE_ANALYTICS_ID: "TBD" #Â override for prod TBD in all other envs
        PAYMENT_REFERENCE_SERVICE_IDENTIFICATION: "DIV1"

        # Features
        FEATURE_IDAM: "true"
        FEATURE_STRATEGIC_PAY: "true"
        FEATURE_NEW_FEES: "true"

        CASE_ORCHESTRATION_SERVICE_DRAFT_URL: "http://div-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/draftsapi/version/1"
        CASE_ORCHESTRATION_SERVICE_URL: "http://div-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DECREE_NISI_FRONTEND_URL: "https://div-dn-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        EVIDENCE_MANAGEMENT_CLIENT_API_URL: "http://div-emca-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        FEES_AND_PAYMENTS_URL: "http://div-fps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        PAYMENT_SERVICE_URL: "http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        IDAM_LOGIN_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login"
        PUBLIC_HOSTNAME: "https://div-pfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal" # override in public facing envs
        PRD_ORGANISATION_API_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/refdata/external/v1/organisations/status"

        IDAM_CLIENT_ID: "divorce"

        EVIDENCE_MANAGEMENT_CLIENT_API_UPLOAD_ENDPOINT: "/emclientapi/version/1/upload"
        EVIDENCE_MANAGEMENT_CLIENT_API_DOWNLOAD_ENDPOINT: "/emclientapi/version/1/download"
        NODE_ENV: "production"
        NODE_PATH: "."
        POST_CODE_URL: "https://api.os.uk/search/places/v1"
        RATE_LIMITER_ENABLED: "false" # seems like this is never enabled?
        RATE_LIMITER_EXPIRE: "3600000"
        RATE_LIMITER_TOTAL: "3600"

        # Court Details
        COURT_EMAIL: "contactdivorce@justice.gov.uk"
        COURT_PHONENUMBER_EN: "0300 303 0642"
        COURT_PHONENUMBER_CY: "0300 303 5171"
        COURT_OPENINGHOURS_EN: "Monday, Wednesday and Friday -phones are open 8am-6pm and Webchat open 8am-8pm. <br>Tuesday and Thursday - Webchat and phones are open 8am-8pm. <br>Saturdays - Webchat and phones are open 8am-2pm."
        COURT_OPENINGHOURS_CY: "Dydd Llun i ddydd Gwener, 8:30am - 5pm"
        COURT_SERVICE_CENTRE_SITEID: "CTSC"
        SERVICE_CENTRE_NAME: "Courts and Tribunals Service Centre"

        WEBCHAT_CHAT_ID: 3833071605d5d4518036a09.30917386 # TODO override per env or move to vault
        WEBCHAT_TENANT: aG1jdHNzdGFnaW5nMDE # TODO override per env or move to vault
        WEBCHAT_BUTTON_NO_AGENTS: 7732814745cac6f4603c4d1.53357933 # TODO override per env or move to vault
        WEBCHAT_BUTTON_AGENTS_BUSY: 2042157415cc19c95669039.65793052 # TODO override per env or move to vault
        WEBCHAT_BUTTON_SERVICE_CLOSED: 20199488815cc1a89e0861d5.73103009 # TODO override per env or move to vault

        ANTENNA_WEBCHAT_URL: "webchat.ctsc.hmcts.net"
        ANTENNA_WEBCHAT_SERVICE: "Divorce"

        FEATURE_DYNATRACE: "false"

        FEATURE_NEW_APP_CUTOFF_DATE_BANNER: "false"
        FEATURE_NEW_APP_CUTOFF: "false"

        ################################################################################################################
        # JS DateTime value representing when the new application cutoff will take effect
        # Servers use UTC!  Adjust values accordingly!
        NEW_APP_CUTOFF_DATE: "2022-03-31T15:00:00"

        # Boolean.  True: New app cutoff date test evaluates true.
        #           False: New app cutoff is evaluated against current server datetime.
        NEW_APP_CUTOFF_DATE_OVERRIDE: false

        # Boolean. True: Test for existence of a caseId evaluates to true.
        #          False: Check for caseId within session object.
        NEW_APP_CUTOFF_CASEID_OVERRIDE: false

        # Array of case states that will trigger a redirect.
        NEW_APP_CUTOFF_REDIRECT_STATES: [
            'AwaitingPayment',
            'AwaitingHWFDecision',
            'AwaitingDocuments',
            'Withdrawn',
            'PendingRejection',
            'Rejected'
        ]

        # Boolean.  True: Case states from sessions will be overridden by NEW_APP_CUTOFF_STATE_TO_CHECK for landing
        #                 page redirection
        #           False: Case states from sessions will be evaluated for landing page redirection
        # NB: Will be ignored if NEW_APP_CUTOFF_STATE_OVERRIDE is True.
        NEW_APP_CUTOFF_USE_STATE_TO_CHECK: false

        # String. Case state to validate against NEW_APP_CUTOFF_REDIRECT_STATES array when
        #         NEW_APP_CUTOFF_USE_STATE_TO_CHECK is True.
        #         Will be ignored if NEW_APP_CUTOFF_STATE_OVERRIDE is True, or NEW_APP_CUTOFF_USE_STATE_TO_CHECK is
        #         False.
        NEW_APP_CUTOFF_STATE_TO_CHECK: 'TestState'

        # Boolean.  True: Case state redirect check evaluates to true.
        #           False: Case state evaluated against array.
        NEW_APP_CUTOFF_STATE_OVERRIDE: false

        # Boolean.  Toggle verbose logging of new app cutoff evaluation steps.
        NEW_APP_CUTOFF_DEBUG: false
        ################################################################################################################

        # Leave AAT as default for now, until we have a release window to change in prod, then switch prod to default
        # COOKIE_DOMAIN: "apply-divorce.service.gov.uk"
        COOKIE_DOMAIN: "Test.Cookie.Domain.Value.Values"


    keyVaults:
        div:
            secrets:
                - session-secret
                - redis-secret
                - idam-secret
                - os-places-token
                - frontend-secret
                - pfe-redis-connection-string
                - AppInsightsInstrumentationKey
                - launchdarkly-key
                - pcq-token-key
                - idam-citizen-username
                - idam-citizen-password

redis:
    cluster:
        enabled: false
        slaveCount: 0
    usePassword: false
    master:
        persistence:
            enabled: false

tags:
    idam-pr: false
    pr: false
