apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  USE_AUTH : "0"
  COURT_EASTMIDLANDS_EMAIL : "eastmidlandsdivorce@hmcts.gsi.gov.uk"
  POST_CODE_ACCESS_TOKEN : ${POST_CODE_ACCESS_TOKEN}
  SESSION_ENCRYPTION_SECRET : ${SESSION_ENCRYPTION_SECRET}
  SECRET: {SECRET}
  IDAM_SECRET: ${IDAM_SECRET}
  MICROSERVICE_KEY: ${MICROSERVICE_KEY}
  COURT_NORTHWEST_CITY : "Liverpool"
  IDAM_LOGIN_URL : "https://idam.preprod.ccidam.reform.hmcts.net/login"
  EVIDENCE_MANAGEMENT_CLIENT_API_HEALTHCHECK_URL : "http://div-emca-aat.service.core-compute-aat.internal/health"
  SERVICE_AUTH_PROVIDER_URL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  IDAM_AUTHENTICATION_HEALHCHECK_URL : "https://idam.preprod.ccidam.reform.hmcts.net/health"
  COURT_SOUTHWEST_CITY : "Southampton"
  PACKAGES_PROJECT : "divorce"
  REFORM_ENVIRONMENT : "aat"
  COURT_SOUTHWEST_SITEID : "AA03"
  WEBSITE_AUTH_ENABLED : "False"
  COURT_SOUTHWEST_NAME : "South West Regional Divorce Centre"
  IDAM_API_URL : "https://preprod-idamapi.reform.hmcts.net:3511"
  COURT_NORTHWEST_NAME : "North West Regional Divorce Centre"
  APPLICATION_INSIGHTS_IKEY : "63c30ef9-a27b-4d38-8afc-4c180fb6ac33"
  COURT_EASTMIDLANDS_NAME : "East Midlands Regional Divorce Centre"
  COURT_EMAIL : "divorce@justice.gov.uk"
  NODE_ENV : "production"
  PUBLIC_PROTOCOL : "https"
  COURT_OPENINGHOURS : "Monday to Friday, 8.30am to 5pm"
  SMARTSURVEY_FEEDBACK_URL : "http://www.smartsurvey.co.uk/s/0QIL4"
  IDAM_APP_HEALHCHECK_URL : "https://preprod-idamapi.reform.hmcts.net:3511/health"
  COURT_NORTHWEST_PHONENUMBER : "0300 303 0642"
  SERVICE_NAME : "divorce-frontend"
  SOUTHWEST_COURTWEIGHT : "0.35"
  FEES_AND_PAYMENTS_HEALTHCHECK_URL : "http://div-fps-aat.service.core-compute-aat.internal/health"
  PACKAGES_ENVIRONMENT : "preprod"
  COURT_WESTMIDLANDS_NAME : "West Midlands Regional Divorce Centre"
  COURT_SOUTHWEST_POBOX : "PO Box 1792"
  REFORM_TEAM : "div"
  CASE_PROGRESSION_SERVICE_DRAFT_URL : "http://div-cps-aat.service.core-compute-aat.internal/draftsapi/version/1"
  COURT_NORTHWEST_POSTCODE : "L2 2BX"
  MICROSERVICE_NAME : "divorce_frontend"
  EVIDENCE_MANAGEMENT_CLIENT_API_UPLOAD_ENDPOINT : "/emclientapi/version/1/upload"
  PAYMENT_SERVICE_HEALTHCHECK_URL : "http://payment-api-aat.service.core-compute-aat.internal/health"
  DIVORCE_HTTP_PROXY : ""
  COURT_EASTMIDLANDS_POBOX : "PO Box 10447"
  SMARTSURVEY_FEEDBACK_DONE_URL : "http://www.smartsurvey.co.uk/s/8RR1T"
  CASE_PROGRESSION_SERVICE_HEALTHCHECK_URL : "http://div-cps-aat.service.core-compute-aat.internal/health"
  UV_THREADPOOL_SIZE : "64"
  WEBSITE_SLOT_POLL_WORKER_FOR_CHANGE_NOTIFICATION : "0"
  COURT_NORTHWEST_OPENINGHOURS : "Monday to Friday, 8.30am to 5pm"
  COURT_EASTMIDLANDS_PHONENUMBER : "0300 303 0642"
  CASE_PROGRESSION_SERVICE_URL : "http://div-cps-aat.service.core-compute-aat.internal/transformationapi/version/1"
  COURT_SOUTHWEST_PHONENUMBER : "0300 303 0642"
  PAYMENT_SERVICE_URL : "http://payment-api-aat.service.core-compute-aat.internal"
  RATE_LIMITER_EXPIRE : "3600000"
  PACKAGES_NAME : "frontend"
  EVIDENCE_MANAGEMENT_CLIENT_API_URL : "http://div-emca-aat.service.core-compute-aat.internal"
  GOOGLE_ANALYTICS_ID : "TBD"
  WEBSITE_LOCAL_CACHE_OPTION : "Always"
  FEATURE_FULL_PAYMENT_EVENT_DATA_SUBMISSION : "1"
  WEBSITE_SITE_NAME : "div-pfe-aat"
  COURT_WESTMIDLANDS_EMAIL : "westmidlandsdivorce@hmcts.gsi.gov.uk"
  FEATURE_REDIRECT_TO_APPLICATION_SUBMITTED : "false"
  HPKP_SHAS : "Naw+prhcXSIkbtYJ0t7vAD+Fc92DWL9UZevVfWBvids=,klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=,grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME="
  COURT_EASTMIDLANDS_CITY : "Nottingham"
  COURT_WESTMIDLANDS_POSTCODE : "ST4 9NH"
  COURT_WESTMIDLANDS_CITY : "Stoke-on-Trent"
  no_proxy : "localhost,127.0.0.0/8,127.0.0.1,127.0.0.1*,local.home,reform.hmcts.net,*.reform.hmcts.net,betaDevBdivorceAppLB.reform.hmcts.net,betaDevBccidamAppLB.reform.hmcts.net,*.internal,*.platform.hmcts.net"
  REDISCLOUD_URL : "redis://ignore:mjh%2FSYWam86tgm9DO3WSfn1tgcUD4ipdDKn03%2B5mplo%3D@div-redis-aat.redis.cache.windows.net:6380?tls"
  COURT_NORTHWEST_EMAIL : "family@liverpool.countycourt.gsi.gov.uk"
  WESTMIDLANDS_COURTWEIGHT : "0.15"
  NORTHWEST_COURTWEIGHT : "0.25"
  WEBSITE_LOCAL_CACHE_SIZEINMB : "300"
  COURT_SOUTHWEST_WEIGHT : "0.20"
  FEATURE_IDAM : "1"
  COURT_WESTMIDLANDS_OPENINGHOURS : "Monday to Friday, 8.30am to 5pm"
  HPKP_MAX_AGE : "86400"
  COURT_WESTMIDLANDS_PHONENUMBER : "0300 303 0642"
  COURT_EASTMIDLANDS_POSTCODE : "NG2 9QN"
  PAYMENT_REFERENCE_SERVICE_IDENTIFICATION : "DIV1"
  COURT_SOUTHWEST_EMAIL : "sw-region-divorce@hmcts.gsi.gov.uk"
  EASTMIDLANDS_COURTWEIGHT : "0.25"
  COURT_SOUTHWEST_POSTCODE : "SO15 9GG"
  REFORM_SERVICE_NAME : "pfe"
  COURT_NORTHWEST_SITEID : "AA04"
  COURT_WESTMIDLANDS_SITEID : "AA02"
  COURT_NORTHWEST_ADDRESSNAME : "Liverpool Civil & Family Court"
  COURT_PHONENUMBER : "0300 303 0642"
  GOOGLE_ANALYTICS_TRACKING_URL : "http://www.google-analytics.com/collect"
  COURT_EASTMIDLANDS_WEIGHT : "0.20"
  COURT_NORTHWEST_STREET : "35 Vernon Street"
  WEBSITE_NODE_DEFAULT_VERSION : "8.9.4"
  COURT_WESTMIDLANDS_POBOX : "PO Box 3650"
  COURT_EASTMIDLANDS_OPENINGHOURS : "Monday to Friday, 8.30am to 5pm"
  PACKAGES_VERSION : "3.0.0"
  SERVICE_AUTH_PROVIDER_HEALTHCHECK_URL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal/health"
  SLOT : "PRODUCTION"
  RATE_LIMITER_TOTAL : "3600"
  FEES_AND_PAYMENTS_URL : "http://div-fps-aat.service.core-compute-aat.internal"
  COURT_SOUTHWEST_OPENINGHOURS : "Monday to Friday, 8.30am to 5pm"
  COURT_EASTMIDLANDS_SITEID : "AA01"
  DEPLOYMENT_ENV : "preprod"
  PUBLIC_HOSTNAME : "div-pfe-aat.service.core-compute-aat.internal"
  COURT_NORTHWEST_WEIGHT : "0.25"
  POST_CODE_URL : "https://postcodeinfo.service.justice.gov.uk"
  APPINSIGHTS_INSTRUMENTATIONKEY : "63c30ef9-a27b-4d38-8afc-4c180fb6ac33"
  COURT_WESTMIDLANDS_WEIGHT : "0.35"