# ---
# Used when running the app locally.
# Rename this file to `development.yaml`.
# This file is used for any development config which should not be version controlled.
# For example, you can add a LaunchDarkly SDK here to test locally and it will not be pushed to Git.
# ---

showSitemap: true
featureToggles:
  launchDarklyKey: 'Insert LD SDK here'
